import 'package:flutter/material.dart';


const Color kDBackgroundColor = Color(0xFF004466);
const Color kDBackgroundColorCalendar = Color(0xFFD2D2D2);
const String kDFontFamilyHeader = 'Righteous';
const String kDFontFamilyParagraph = 'Nunito';
const double kDFontSizeText = 18;
const double kDFontSizeHeader = 22;
const Color kDColorTextWhite = Colors.white;
const Color kDColorTextColorBackground = Color(0xFFFFFFFF);
const Color kDTextBackgroundTransparent = Color(0x99000000);
const Color kDBoxShadowColor = Color(0xFF2C3E50);
const Color kDColorOfBackgroundHeader =  Color(0xB3FFFFFF);
const Color kDColorFloatingButton = Color(0xFFA63D40);
const Color kDColorPlayerBackground = Color(0xFFE9B872);
const Color kDColorPlayerButton = Color(0xFFA63D40);
const Color kDColorWastePlastic = Colors.orangeAccent;
const Color kDColorWasteBio = Colors.brown;
const Color kDColorWastePaper = Colors.blueAccent;
const Color kDColorWasteMixed = Colors.black87;
const double kDPadding = 10.0;
const double kDMargin = 10.0;
const double kDMarginLarger = 30.0;
const double kDMyAppBarHeight = 55.0;
const String kDAppIconPath = 'assets/images/DK_znak_200px.png';
const Color kDividerColor = Color(0xFFA63D40);
DateTime dateTimePicker = DateTime.now();
DateTime dateTimeNow = dateTimePicker;
DateTime dateTimeFirstDay = DateTime.utc(2021, 12, 01);
DateTime dateTimeLastDay = DateTime.utc(2023, 01, 30);
DateTime dateTimeFocusedDay = dateTimeNow;
const BorderRadius kDRadius = BorderRadius.all(Radius.circular(15.0));
const BorderRadius kDRadiusSmall = BorderRadius.all(Radius.circular(10.0));
const BorderRadius kDRadiusLarge = BorderRadius.all(Radius.circular(20.0));
const String versionApp = '1.0.0';
